; Включает кэширование PHP-кода в OPcache для ускорения работы
opcache.enable=1

; Отключает OPcache для CLI (обычно не нужен в консоли)
opcache.enable_cli=1

; Сохраняет PHPDoc-комментарии
opcache.save_comments=1

; Включает все возможные оптимизации кода
opcache.optimization_level=0xffffffff

; Отключает проверку прав доступа к файлам (ускоряет работу)
opcache.validate_permission=0

; Отключает проверку chroot-окружения (если не используется)
opcache.validate_root=0

; Отключает проверку изменений в файлах (требует ручного сброса кэша)
opcache.validate_timestamps=0

; Включает кеширование при поиске файлов в include/require
opcache.revalidate_path=0

; Отключает использование Huge Pages (требует настройки ОС)
opcache.huge_code_pages=0
